- name: Build the app
  run: npm run build

- name: Remove .next/cache
  run: rm -rf .next/cache

- name: Deploy to Azure Static Web Apps
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_BUSH_0FF8B0003 }}
    github_id_token: ${{ steps.idtoken.outputs.result }}
    action: "upload"
    app_location: "/"
    output_location: ".next"
